# Generated by Django 4.0.6 on 2022-07-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='person_to_task',
            field=models.CharField(default='Null', max_length=200),
            preserve_default=False,
        ),
    ]
